apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - configMapRef:
                name: payment-db-config
          ports:
            - containerPort: 5432