apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  POSTGRES_HOST: "product-db-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "product_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  KAFKA_CREATE_INVENTORY_COMMAND_TOPIC: "create.inventory.command"
  INVENTORY_SVC: "http://inventory-service:8083"
