server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, roles, email
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUE_URL}
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUE_URL}

rest.integration:
  product-service: ${PRODUCT_SVC}
  inventory-service: ${INVENTORY_SVC}
  order-service: ${ORDER_SVC}
  payment-service: ${PAYMENT_SVC}


#eureka:
#  integration:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
