apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - configMapRef:
                name: inventory-db-config
            - secretRef:
                name: inventory-db-secret
          ports:
            - containerPort: 5432