
server:
  port: 8082

app:
  kafka:
    topic:
      create-inventory-command: ${KAFKA_CREATE_INVENTORY_COMMAND_TOPIC}

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUE_URL}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true

#  kafka:
#    bootstrap-servers: ${KAFKA_HOST}
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#    consumer:
#      group-id: product-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

rest.integrations:
  inventory-service: ${INVENTORY_SVC}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka