KC_CLIENT_ID: test-microservices
KC_ISSUE_URL: https://usw2.auth.ac/auth/realms/microservices-kz
KC_SECRET: QGtmHMZ1Vgai49ztBuZ6rHrrDdgGPNMz
KAFKA_HOST: kafka-service:9092
POSTGRES_HOST: localhost
POSTGRES_PORT: 5433
POSTGRES_DB: product_db
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
KAFKA_CREATE_INVENTORY_COMMAND_TOPIC: create.inventory.command
INVENTORY_SVC: http://inventory-service:8083