apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  POSTGRES_HOST: "payment-db-service:5432"
  POSTGRES_DB: "payment_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  KAFKA_CREATE_PAYMENT_COMMAND_TOPIC: "payment.create.command"
  KAFKA_PAYMENT_COMPLETED_TOPIC: "payment.completed"
  KAFKA_PAYMENT_FAILED_TOPIC: "payment.failed"
